name: my-app
services:
  - name: backend
    source_dir: /api
    dockerfile_path: Dockerfile
    github:
      repo: nathan-moore-97/nellys
      branch: dockerize
    envs:
      - key: DATABASE_URL
        value: sqlite:///app/data/database.sqlite
      - key: NEWSLETTER_ADMIN_EMAIL
        type: SECRET
        value: ""
      - key: EMAIL_SERVICE
        type: SECRET
        value: ""
      - key: EMAIL_HOST
        type: SECRET
        value: ""
      - key: EMAIL_USERNAME
        type: SECRET
        value: ""
      - key: EMAIL_APP_PASSWORD
        type: SECRET
        value: ""
      - key: WEB_APP_ROOT_URL
        type: SECRET
        value: ""
      - key: ENVIORNMENT
        value: prod
      - key: LOG_LEVEL
        value: warn
      - key: AWS_REGION
        type: SECRET
        value: ""
      - key: AWS_ACCESS_KEY_ID
        type: SECRET
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        type: SECRET
        value: ""
      - key: GALLERY_BUCKET_NAME
        type: SECRET
        value: ""
      - key: JWT_SECRET
        type: SECRET
        value: ""
      - key: JWT_REFRESH_SECRET
        type: SECRET
        value: ""
      - key: JWT_REGISTRATION_SECRET
        type: SECRET
        value: ""
    http_port: 3000
    instance_size_slug: basic-xxs

  - name: frontend
    source_dir: /client
    dockerfile_path: Dockerfile
    github:
      repo: nathan-moore-97/nellys
      branch: dockerize
    envs:
      - key: VITE_API_URL
        value: ${backend.URL}
      - key: VITE_GMAPS_API_KEY
        type: SECRET
        value: ""
      - key: VITE_GMAPS_PLACE_ID
        type: SECRET
        value: ""
    routes:
      - path: /
    instance_size_slug: basic-xxs